# 1.Print 'Hello HCIA'.

In [4]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
x=3
y=4
x+y

7

# 3.Define a list and replicate in three different ways.

In [50]:
import copy;
list1 = [1,2,3,4,5];
n_list = copy.copy(list1);
print(n_list);
n_list = list1;
print(n_list);
print(list1);
print(list1[:]);
n_list = list1[:];
print(list1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


# 4.Define two lists and merge them together.

In [1]:
a = [2, 4, 6];
b = [3, 4, 9];
a + b

[2, 4, 6, 3, 4, 9]

# 5. Get the last element of the list and print it.

In [2]:
a = [9, 0, 3, 13, 89];
a[len(a)-1]

89

# 6.Define a tuple that contains only one element.

In [4]:
t = (2);
print(t)

2


# 7.Define a three-line long string.

In [9]:
a = ('''3 4 5 9;
8 0 9;
6 7 3 0 1.
''')
print(a)

3 4 5 9;
8 0 9;
6 7 3 0 1.



# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [21]:
t=[2,4,10,45,99,0]
for i in t[1:6]:
    print(i)
print(t)

4
10
45
99
0
[2, 4, 10, 45, 99, 0]


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [28]:
x = 8;
y = 6;
Mul = x*y;
print(Mul)

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [35]:
import numpy;
numpy.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [34]:
import numpy;
numpy.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [40]:
x = numpy.arange(15,);
x = x.reshape(3,5);
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [49]:
a = numpy.arange(8).reshape(4,2);
b = numpy.arange(8).reshape(2,4);
numpy.matmul(a,b)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47],
       [28, 41, 54, 67]])